-- 🎲 抽奖系统数据库初始化脚本 (PostgreSQL)

-- 创建抽奖活动表
CREATE TABLE IF NOT EXISTS LuckyDrawActivities (
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(200) NOT NULL,
    Description TEXT,
    Prize VARCHAR(500) NOT NULL,
    MaxParticipants INTEGER NOT NULL DEFAULT 100,
    CurrentParticipants INTEGER NOT NULL DEFAULT 0,
    WinnerCount INTEGER NOT NULL DEFAULT 1,
    Status INTEGER NOT NULL DEFAULT 0,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DrawTime TIMESTAMP NULL
);

COMMENT ON TABLE LuckyDrawActivities IS '抽奖活动表';
COMMENT ON COLUMN LuckyDrawActivities.Name IS '活动名称';
COMMENT ON COLUMN LuckyDrawActivities.Description IS '活动描述';
COMMENT ON COLUMN LuckyDrawActivities.Prize IS '奖品';
COMMENT ON COLUMN LuckyDrawActivities.MaxParticipants IS '最大参与人数';
COMMENT ON COLUMN LuckyDrawActivities.CurrentParticipants IS '当前参与人数';
COMMENT ON COLUMN LuckyDrawActivities.WinnerCount IS '获奖者数量';
COMMENT ON COLUMN LuckyDrawActivities.Status IS '状态: 0-未开始, 1-进行中, 2-已完成, 3-已取消';
COMMENT ON COLUMN LuckyDrawActivities.CreatedAt IS '创建时间';
COMMENT ON COLUMN LuckyDrawActivities.DrawTime IS '开奖时间';

CREATE INDEX IF NOT EXISTS idx_status ON LuckyDrawActivities (Status);
CREATE INDEX IF NOT EXISTS idx_created_at ON LuckyDrawActivities (CreatedAt);

-- 创建参与者表
CREATE TABLE IF NOT EXISTS Participants (
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ActivityId INTEGER NOT NULL,
    Name VARCHAR(100) NOT NULL,
    Contact VARCHAR(100) NOT NULL,
    LuckyNumber VARCHAR(20) NOT NULL,
    IsWinner BOOLEAN NOT NULL DEFAULT FALSE,
    JoinedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_activity FOREIGN KEY (ActivityId) REFERENCES LuckyDrawActivities (Id) ON DELETE CASCADE
);

COMMENT ON TABLE Participants IS '参与者表';
COMMENT ON COLUMN Participants.ActivityId IS '活动ID';
COMMENT ON COLUMN Participants.Name IS '参与者名称';
COMMENT ON COLUMN Participants.Contact IS '联系方式';
COMMENT ON COLUMN Participants.LuckyNumber IS '幸运号码';
COMMENT ON COLUMN Participants.IsWinner IS '是否中奖';
COMMENT ON COLUMN Participants.JoinedAt IS '参与时间';

CREATE INDEX IF NOT EXISTS idx_activity_id ON Participants (ActivityId);
CREATE INDEX IF NOT EXISTS idx_is_winner ON Participants (IsWinner);
CREATE INDEX IF NOT EXISTS idx_lucky_number ON Participants (LuckyNumber);

-- 插入示例数据
INSERT INTO LuckyDrawActivities (Name, Description, Prize, MaxParticipants, WinnerCount, Status) VALUES
('🎄 圣诞节抽奖活动', '参与圣诞节抽奖，赢取丰厚大奖！', 'iPhone 15 Pro Max', 1000, 3, 1),
('🧧 新年红包雨', '新年福利，人人有机会！', '888元现金红包', 500, 10, 0);